name: Release docker image

on:
  workflow_dispatch:

jobs:
  release-docker-image:

    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-3
      ECR_REPOSITORY: hei-admin-api

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # secrets.GITHUB_TOKEN is not enough for releasing on protected branch
          # Use a Personal Access Token from someone who has sufficient privileges
          token: ${{ secrets.GH_TOKEN_FOR_CONVENTIONAL_CHANGELOG }}


      #######################################################
      ############## DETERMINE NEXT VERSION #################
      #######################################################

      # We will use conventional-changelog which only supports yaml, yml and toml version file
      - name: From gradle.properties to version.yml
        run: |
          cp gradle.properties version.yml
          sed -i 's/=/: /g' version.yml
          git status

      # conventional-ch increments the patch version even when
      # it skipped commiting due to empty changelog. In such a case,
      # we have to retrieve the old (unchanged) version using our own means.
      # https://github.com/conventional-changelog/standard-version/issues/730

      - name: Read old version file
        id: read-old-version
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: version.yml
          version: version
      - name: Conventional changelog
        id: conventional-ch
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GH_TOKEN_FOR_CONVENTIONAL_CHANGELOG }}
          git-message: 'ci(release): {version}'
          release-count: '10'
          version-file: './version.yml'
          version-path: 'version'
          skip-on-empty: 'true'
          skip-version-file: 'false'
          skip-commit: 'false'
      - name: Read new version file
        id: read-new-version
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: version.yml
          version: version
      - name: Put correct version into GITHUB_ENV
        run: |
          if [ ${{ steps.conventional-ch.outputs.skipped == 'false' }} ]
          then
            echo "image_version=${{ steps.read-new-version.outputs.version }}" >> $GITHUB_ENV
          else
            echo "image_version=${{ steps.read-old-version.outputs.version }}" >> $GITHUB_ENV
          fi

      - name: If version incremented then go from version.yml to gradle.properties and commit
        if: ${{ steps.conventional-ch.outputs.skipped == 'false' }} 
        run: |
          cp version.yml gradle.properties
          sed -i 's/: /=/g' gradle.properties
          rm version.yml

          git add version.yml gradle.properties
          git commit --amend --no-edit
          git push -f
          # Also update tag since commit was amended
          git tag -d v${{ env.image_version }}
          git tag v${{ env.image_version }}
          git push --delete origin v${{ env.image_version }}
          git push --tags


      #######################################################
      ######### BUILD AND RELEASE TO AWS ECR ################
      #######################################################

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build
        run: ./gradlew build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
      - name: Build, tag, and push image to AWS ECR
        # do NOT skip step based on conventional-ch output
        # because we want to be able to re-publish image
        # when previous release attempt succeeded commiting but failed publishing
        # if: ${{ steps.conventional-ch.outputs.skipped }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # do NOT use steps.conventional-ch.outputs.version|tag because
          # (1) they are NOT set when previous release attempt succeeded commiting but failed publishing
          # (2) version is still incremented even if release was skipped due to empty changelog
          IMAGE_TAG: ${{ env.image_version }}
        run: |
          ls build/libs/
          docker build --build-arg version=$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
